# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Not Bored!"
email: xanderk@nobo.red
description: >- # this means to ignore newlines until "baseurl:"
  A blog containing the ADD ramblings of someone who is never bored. Topics include
  Pentesting, hacking, cybersecurity, physical security, video games, communication skills, 
  rants, and anything else that is deemed interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.notbo.red" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@x_a_n_d_e_r_k"
repository: "x-a-n-d-e-r-k/x-a-n-d-e-r-k.github.io"
github_username:  x-a-n-d-e-r-k
github: [metadata]

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values: 
      show_date: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/